// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw9O91jKi7W6UGW_EE8PVIYdxVPKk9zg8',
    appId: '1:794039290970:web:da7a73444c5609eda55c63',
    messagingSenderId: '794039290970',
    projectId: 'diff-auth',
    authDomain: 'diff-auth.firebaseapp.com',
    storageBucket: 'diff-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6P-YQ49DB_xkkcwECCVgZAwkumloLgo',
    appId: '1:794039290970:android:d47fb295ca98ba32a55c63',
    messagingSenderId: '794039290970',
    projectId: 'diff-auth',
    storageBucket: 'diff-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoCLRjMWYqKcabJvXi81ycEZcN_7Deil8',
    appId: '1:794039290970:ios:8c2787d4605cd22da55c63',
    messagingSenderId: '794039290970',
    projectId: 'diff-auth',
    storageBucket: 'diff-auth.appspot.com',
    iosClientId: '794039290970-lu72kmlsiobr3asiu2r5luijm5j5o64p.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoCLRjMWYqKcabJvXi81ycEZcN_7Deil8',
    appId: '1:794039290970:ios:90fb93aa2f756a8ca55c63',
    messagingSenderId: '794039290970',
    projectId: 'diff-auth',
    storageBucket: 'diff-auth.appspot.com',
    iosClientId: '794039290970-k1sct8p0f2rv74rbrm21bouoi1iokm97.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin.RunnerTests',
  );
}
